name: DevBuildTest

trigger:
- develop

pr: none

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '88f6f655-7e0a-4d38-86b2-846da9eea546'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.9
  pythonVersion: '3.9'  


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r Application/requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
- template: .\templates\deploy_app.yml
  parameters:
    resourceGroupTFStateFile: test-tfstate
    storageAccountNameTFSStateFile: djpythonapp1testtfstate
    resourceGroup: test
    appServicePlanName: djpythonapp1-test
    appInsightsName: djpythonapp1-test
    appServiceName: djpythonapp1-test
    pythonVersion: $(pythonVersion)
    vmImageName: $(vmImageName)
    environmentName: "test"
    azureServiceConnectionId: $(azureServiceConnectionId)
    dependsOn:
      - Build
      - DeployTF
    location: "Central US"
    buildID: $(Build.BuildId)


